import type { Chat } from "./types";

export const initialChats: Chat[] = [
  {
    id: "vlogo",
    name: "Telegram News & Tips Channel",
    status: "154,200 subscribers",
    avatarText: "T",
    avatarBg: "bg-[#20c997]",
    isChannel: true,
    phone: "Channel Link: t.me/telegram_tips",
    notifications: false,
    messages: [
      {
        id: "m1",
        sender: "them",
        text: "How would you rate the quality of today's discussion?",
        time: "Apr 1",
        read: true,
      },
    ],
    sharedMedia: [
      "https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?w=300&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=300&auto=format&fit=crop",
    ],
  },
  {
    id: "deleted_1",
    name: "Deleted Account",
    status: "last seen a long time ago",
    avatarText: "👤",
    avatarBg: "bg-gray-300",
    phone: "Hidden",
    notifications: false,
    messages: [
      {
        id: "d1",
        sender: "them",
        text: "Deleted Account joined Telegram",
        time: "Apr 1",
        read: true,
      },
    ],
    sharedMedia: [],
  },
  {
    id: "deleted_2",
    name: "Deleted Account",
    status: "last seen a long time ago",
    avatarText: "👤",
    avatarBg: "bg-gray-300",
    phone: "Hidden",
    notifications: false,
    messages: [
      {
        id: "d2_1",
        sender: "them",
        text: "Hello, is the project ready yet?",
        time: "Mar 30",
        read: true,
      },
    ],
    sharedMedia: [],
  },
  {
    id: "c_tuyet",
    name: "Sarah Watson",
    status: "last seen 3 days ago",
    avatarText: "SW",
    avatarBg: "bg-[#ff6b6b]",
    phone: "+1 202 555 0143",
    notifications: true,
    messages: [
      {
        id: "ct1",
        sender: "them",
        text: "Sarah Watson joined Telegram",
        time: "Mar 19",
        read: true,
      },
    ],
    sharedMedia: [],
  },
  {
    id: "giang",
    name: "David Smith",
    status: "online",
    avatarText: "DS",
    avatarBg: "bg-[#4dabf7]",
    phone: "+1 202 555 0192",
    notifications: true,
    messages: [
      {
        id: "g1",
        sender: "them",
        text: "David Smith joined Telegram",
        time: "Jan 12",
        read: true,
      },
    ],
    sharedMedia: [],
  },
  {
    id: "me",
    name: "Mom",
    status: "last seen 5 minutes ago",
    avatarUrl:
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=100&auto=format&fit=crop",
    phone: "+1 202 555 0115",
    notifications: true,
    messages: [
      {
        id: "m_me1",
        sender: "them",
        text: "Mom joined Telegram. Take care!",
        time: "Dec 19",
        read: true,
      },
    ],
    sharedMedia: [
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300&auto=format&fit=crop",
    ],
  },
  {
    id: "van_chay",
    name: "Michael Scott",
    status: "last seen a long time ago",
    avatarText: "MS",
    avatarBg: "bg-[#9c63e0]",
    phone: "+1 202 555 0184",
    notifications: true,
    messages: [
      {
        id: "vc1",
        sender: "them",
        text: "I am running Facebook ads for our client",
        time: "18:01",
        read: true,
      },
      {
        id: "vc2",
        sender: "me",
        text: "Are you moving to California next year?",
        time: "18:07",
        read: true,
      },
      {
        id: "vc3",
        sender: "me",
        text: "Our team lead has already arrived there",
        time: "18:07",
        read: true,
      },
      {
        id: "vc4",
        sender: "them",
        text: "Yes, I am!",
        time: "18:07",
        read: true,
      },
      {
        id: "vc5",
        sender: "them",
        text: "Haha we should totally catch up then! :p",
        time: "18:07",
        read: true,
      },
      { id: "vc6", sender: "them", text: "😂 😆", time: "18:07", read: true },
      {
        id: "vc7",
        sender: "me",
        text: "Let me know when you arrive",
        time: "18:08",
        read: true,
      },
      {
        id: "vc8",
        sender: "me",
        text: "He's been there for a few months now",
        time: "18:08",
        read: true,
      },
      {
        id: "vc9",
        sender: "me",
        text: "They said it is highly profitable there",
        time: "18:08",
        read: true,
      },
      {
        id: "vc10",
        sender: "them",
        text: "Haha are you going too?",
        time: "18:08",
        read: true,
      },
      {
        id: "vc11",
        sender: "me",
        text: "No, I need to take it slow",
        time: "19:34",
        read: true,
      },
      {
        id: "vc12",
        sender: "me",
        text: "They keep inviting me to join them",
        time: "19:34",
        read: true,
      },
      {
        id: "vc13",
        sender: "me",
        text: "I told them I'll wait to see how it goes first :))",
        time: "19:34",
        read: true,
      },
      { id: "vc14", sender: "them", text: "😂", time: "19:35", read: true },
      {
        id: "vc15",
        sender: "them",
        text: "Yeah, definitely",
        time: "19:35",
        read: true,
      },
    ],
    sharedMedia: [
      "https://images.unsplash.com/photo-1547928576-a4a33237eceb?w=300&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=300&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=300&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=300&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=300&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?w=300&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=300&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=300&auto=format&fit=crop",
    ],
  },
  {
    id: "ds_uid",
    name: "Marketing Support",
    status: "last seen within a week",
    avatarText: "M",
    avatarBg: "bg-[#1877f2]",
    phone: "+1 202 555 0103",
    notifications: false,
    messages: [
      {
        id: "ds1",
        sender: "me",
        text: "ORGANIC TREATMENT FOR PLANTS - DISCOUNTS ON FIRST PURCHASE...",
        time: "Oct 25",
        read: true,
      },
    ],
    sharedMedia: [
      "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=300&auto=format&fit=crop",
    ],
  },
  {
    id: "edit_f5",
    name: "F5 Photo Editors",
    status: "last seen within a month",
    avatarUrl:
      "https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?w=100&auto=format&fit=crop",
    phone: "+1 202 555 0157",
    notifications: true,
    messages: [
      {
        id: "ed1",
        sender: "me",
        text: "DecalDesign.psd",
        time: "Jul 25",
        read: true,
      },
    ],
    sharedMedia: [
      "https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?w=300&auto=format&fit=crop",
    ],
  },
  {
    id: "deleted_3",
    name: "Deleted Account",
    status: "last seen a long time ago",
    avatarText: "👤",
    avatarBg: "bg-gray-300",
    phone: "Hidden",
    notifications: false,
    messages: [
      {
        id: "d3_1",
        sender: "them",
        text: "Deleted Account Joined Telegram",
        time: "Jul 25",
        read: true,
      },
    ],
    sharedMedia: [],
  },
  {
    id: "deleted_4",
    name: "Deleted Account",
    status: "last seen a long time ago",
    avatarText: "👤",
    avatarBg: "bg-gray-300",
    phone: "Hidden",
    notifications: false,
    messages: [
      {
        id: "d4_1",
        sender: "them",
        text: "Photo message received",
        time: "Jul 23",
        read: true,
      },
    ],
    sharedMedia: [],
  },
];
